language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: 1.0
    - julia: 1.1
    - julia: 1.3
    - julia: nightly
script:
  - julia --project -e 'import Pkg; Pkg.build(); Pkg.instantiate()'
  - julia --project -e 'import Pkg; Pkg.test();'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
