# Configuration default values.
# - These values can be overwritten with a custom `config.yml` in the repository base directory.
# - In the path settings, `./` denotes the repository base directory and is replaced upon loading.
paths:
  additional_data: []
  data: ./data
  database: ./data/database.sqlite
  results: ./results
multiprocessing:
  run_parallel: true
caching:
  reset_cache: true  # Reset the cache on each restart of FLEDGE, to incorporate changes in the database.
  cache_building_models: true
optimization:
  solver_name: gurobi  # Must be valid input string for Pyomo's `SolverFactory`.
  show_solver_output: true  # If True, activate verbose solver output.
tests:
  scenario_name: singapore_6node  # Defines scenario which is considered in tests.
  test_examples: true
logs:
  level: info  # Choices: `debug`, `info`, `warn`, `error`.
  format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
plots:
  matplotlib_style: seaborn-colorblind
  colormap: viridis_r
  font_family: ['Arial', 'Helvetica']
  add_basemap: false  # If True, add basemap layer to grid plots for orientation. Requires installation of `contextily`.
